my_tuple = ('p','e','r','m','i','t')
print(my_tuple[0])   
print(my_tuple[5])  
print(my_tuple[-1])
print(my_tuple[-6])
n_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(n_tuple[0][3])     
print(n_tuple[1][1])  
